In [1]:
###Write a function so that the columns of the output matrix are powers of the input vector. 

In [10]:
import numpy as np
def Vect(x,N,increasing=False):
    if increasing==False:
        a=np.column_stack([x**(N-1-i) for i in range(N)])
        print(a)
    else:
        a=np.column_stack([x**(N-1-i) for i in range(N)])
        print(np.flip(a,1))
    
inp = np.array([1,2,3,4,5])
no = 3
print('When Increasing is False')
op=Vect(inp,no,False)

inp = np.array([1,2,3,4,5])
no = 3
print('When Increasing is True')
op=Vect(inp,no,True)



When Increasing is False
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
When Increasing is True
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


In [11]:
###Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
import numpy as np
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a=np.array(x)
m=3
n=[]
for i in range(len(a)-m+1):
    b=a[i]
    sum=0
    for j in range(0,m):
        sum=sum+a[i+j]
    n.append(sum/m)
print(n) 

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
